---
title: "Thesis"
output: html_notebook
---

```{r}
library(quanteda.textplots)
```

```{r}
p2022_merged_toks$group <- "activists"
c2022_merged_toks$group <- "skeptics"

complete = p2022_merged_toks + c2022_merged_toks
```

```{r}
#complete
```


# Create WordCloud of all Climate Compounds

```{r}
# complete corpus 
pro2022$group <- "activists"
contra2022$group <- "skeptics"
complete = pro2022 + contra2022

#summary(complete, n =4342)
```

```{r}
complete_dfm <- dfm(complete)
```
```{r}
dtm <- as.DocumentTermMatrix(complete_dfm, weighting = weightTf)
```
```{r}
tdm <- as.TermDocumentMatrix(complete_dfm, weighting = weightTf) %>%
  as.matrix()

tdm

colnames(tdm) <- c("Activists","Skeptics")

print(xtable(head(tdm)), type="html")
```


```{r}
p <- dfm(pro2022)
p$group <- "activists"

c <- dfm(contra2022)
c$group <- "skeptics"

c_subset <- dfm(c) %>%
    dfm_select(pattern = compounds, valuetype = "glob")

p_subset <- dfm(p) %>%
    dfm_select(pattern = compounds, valuetype = "glob")

common <- dfm_match(c_subset, featnames(p_subset))
common <- dfm_toupper(common)
```

```{r}
featnames(test)
```


```{r}
dfmat2 <- complete %>%
    corpus_subset(group %in% c("activists", "skeptics")) %>%
    dfm() %>%
    dfm_select(pattern = compounds, valuetype = "glob")

#dfmat2 <- dfm_toupper(dfmat2)


dfmat2 <- dfm_group(dfmat2, dfmat2$group)

#set.seed(27)
textplot_wordcloud(dfmat2, comparison = TRUE,
                   color = c("darkgreen", "lightblue"))

textplot_wordcloud(common, color="lightblue")

#ggsave("wordcloud.png", dpi=300, dev='png', height=6, width=12, units="in")

#commonality.cloud(dfmat2,)
```




